/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_AccountTest
{
    @IsTest
     private static void testTrigger()
    {
        
        //MDL_UtilClass_TestClass utilclass = new MDL_UtilClass_TestClass();
        //Deactivate_Trigger_for_data_load__c dtc = new Deactivate_Trigger_for_data_load__c();
        //dtc.Deactivate_trigger__c = false;
        //dtc.name = 'Deactivate dlrs trigger';
        //dtc.getInstance('Deactivate dlrs trigger').Deactivate_trigger__c = false; 
        //insert dtc;
       
        // Force the dlrs_AccountTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        //dlrs.RollupService.testHandler(new Account());   
    }
}