@isTest(SeeAllData=true)
public class RHX_TEST_SBQQ_Subscription {
 static testMethod void RHX_Testmethod() {
        List<sObject> sourceList = [SELECT Id 
                   FROM SBQQ__Subscription__c ORDER BY LastModifiedDate DESC LIMIT 1];
        if(sourceList.size() == 0) {
            sourceList.add(
                    new SBQQ__Subscription__c()
            );
        }
            

       rh2.ParentUtil.UpsertRollupTestRecords( sourceList );
    }
}